### ISSUE TITLE
Development status

### ISSUE THREAD

**Issue by nxrighthere** [rawrtc/rawrtc-data-channel#26]
Lennart, I wonder, does this data channel implementation is mature enough for networking applications which are a few months away from production? The primary goals are reliability with low-latency/minimized head-of-line blocking, and fluent ordered/unordered delivery across multiple channels.

**Comment by lgrahl** [comment]
There may be a couple of people using it in production but I haven't gotten any negative or positive feedback, yet. I guess there's only one way to find out if it's mature enough and it also depends on a few factors:

* Do you use RAWRTC with its ICE stack? If yes, there are a couple of bugs that have been addressed already but not yet merged (such as https://github.com/rawrtc/rawrtc/pull/109).
* Be aware of stream monopolisation when sending large messages, see #14. (I don't believe there are any implementations so far which don't suffer from this.) It's possible to work around it by sending large messages in chunks which needs to be done anyway if you want to talk to Chromium-based browsers.
* There is an unbounded outgoing message queue which may fill up if the receiving end is too slow. I'm open for proposals to change this.

**Comment by nxrighthere** [comment]
@lgrahl I finally finished data channels integration with a custom layer on top of SCTP into the application, and after some slight changes, everything works great! Latency and throughput are very satisfying I couldn't ask for more, thank you for your work. 😺

The code is understandable and convenient to work with (I'm also looked at [Mozilla's implementation](https://github.com/mozilla/gecko-dev/blob/master/netwerk/sctp/datachannel/DataChannel.cpp) to understand how things work under the hood. If you don't mind, I'll take some parts from your implementation for my next project that aims for multiplayer games using SCTP, would love to hear your review when I finish doing this and publish a code. Cheers!

**Comment by nxrighthere** [comment]
Ah, forgot to ask one question. I saw that `SCTP_PEER_ADDR_CHANGE` is commented out in your code, in what circumstances this notification is triggered?

**Comment by lgrahl** [comment]
That's great news! :tada:

If you've encountered areas where you think it could use a bit of polishing, I'm open for suggestions.

> If you don't mind, I'll take some parts from your implementation for my next project [...]

Sure, it's BSD-2 licensed after all.

> [...] would love to hear your review when I finish doing this and publish a code.

Feel free to ping me.

> I saw that `SCTP_PEER_ADDR_CHANGE` is commented out in your code, in what circumstances this notification is triggered?

In our case, never. This would be triggered if you had multiple IP addresses associated to an SCTP assocation (multi-homed). I guess I should remove that line. See also [RFC 6458](https://tools.ietf.org/html/rfc6458#page-45) for this and other events.

**Comment by nxrighthere** [comment]
@lgrahl Lennart, [here's](https://github.com/nxrighthere/HyperNet) the initial implementation. The code itself is amalgamated into a single header. I've tried to keep it as thin as possible on top of SCTP, and I took some parts from your code but the approach of using SCTP streams there is different.

Any advice or notes about things that I should be aware of is highly welcome.
